<%@ include file="navbar.jsp" %>

<div class="row justify-content-center">
    <div class="col-lg-6 col-md-8">
        
        <div class="card bg-dark-card border-neon-pink p-4 pulse-glow text-center">
            <h3 class="fw-bold mb-3 text-neon-pink"><i class="bi bi-box-arrow-in-right me-2"></i>JOIN GAME SESSION</h3>
            <p class="text-muted-custom small mb-4">Enter the 6-character alphanumeric game code generated by your opponent to join their arena session.</p>
            
            <div class="mb-4">
                <input type="text" id="gameCodeInputPage" class="form-control form-control-dark text-center fw-bold fs-3 tracking-wide text-uppercase" placeholder="ENTER CODE" maxlength="6" style="height: 60px;">
                <div class="invalid-feedback text-center mt-2 fs-6" id="join-game-error-page"></div>
            </div>

            <!-- Join Button -->
            <button onclick="joinGameFromPage()" class="btn btn-neon-pink w-100 py-3 d-flex align-items-center justify-content-center gap-2 mb-2" id="joinBtnPage">
                <i class="bi bi-play-fill fs-5"></i>
                <span>ENTER THE ARENA</span>
                <div class="spinner-border spinner-border-sm d-none" id="joinSpinnerPage" role="status"></div>
            </button>
            
            <a href="/dashboard" class="btn btn-outline-secondary w-100 text-muted-custom">
                BACK TO DASHBOARD
            </a>
        </div>
        
    </div>
</div>

<!-- Global Toast Container -->
<div class="toast-container-custom" id="toastContainer"></div>

<script>
    async function joinGameFromPage() {
        const input = document.getElementById('gameCodeInputPage');
        const errDiv = document.getElementById('join-game-error-page');
        const spinner = document.getElementById('joinSpinnerPage');
        const submitBtn = document.getElementById('joinBtnPage');
        
        const code = input.value.trim().toUpperCase();
        
        errDiv.innerText = '';
        input.classList.remove('is-invalid');
        
        if (code.length !== 6) {
            input.classList.add('is-invalid');
            errDiv.innerText = 'Game code must be exactly 6 characters.';
            return;
        }

        spinner.classList.remove('d-none');
        submitBtn.disabled = true;

        try {
            const response = await fetch(`/api/game/join?code=${code}`, { method: 'POST' });
            if (response.ok) {
                const gameSession = await response.json();
                if (gameSession.status === 'PLAYING') {
                    window.location.href = `/game/board/${gameSession.id}`;
                } else {
                    window.location.href = `/game/waiting/${gameSession.id}`;
                }
            } else {
                const errorMsg = await response.text();
                input.classList.add('is-invalid');
                errDiv.innerText = errorMsg || 'Invalid or full game room.';
            }
        } catch (error) {
            console.error("Error joining game:", error);
            input.classList.add('is-invalid');
            errDiv.innerText = 'Server error. Please try again.';
        } finally {
            spinner.classList.add('d-none');
            submitBtn.disabled = false;
        }
    }
</script>

<%@ include file="footer.jsp" %>
